;;; doom-wallust-colors.el --- Generated by Wallust -*- lexical-binding: t; -*-
;;
;; This file is auto-generated by Wallust's template engine.  Do not edit by hand.
;;

{% set bg = background %}
{% set fg = foreground %}


(setq doom-wallust-generated-palette
      '((background . "{{ bg }}")
        (foreground . "{{ fg }}")
        (cursor . "{{ cursor_color }}")
        (color0 . "{{ color0 | saturate(0.5) }}")
        (color1 . "{{ color1 |  saturate(0.5)  }}")
        (color2 . "{{ color2 |  saturate(0.5)  }}")
        (color3 . "{{ color3 |  saturate(0.5)  }}")
        (color4 . "{{ color4 |  saturate(0.5)  }}")
        (color5 . "{{ color5 |  saturate(0.5) }}")
        (color6 . "{{ color6 |  saturate(0.5) }}")
        (color7 . "{{ color7 |  saturate(0.5) }}")
        (color8 . "{{ color8 |  saturate(0.5) }}")
        (color9 . "{{ color9 |  saturate(0.5) }}")
        (color10 . "{{ color10 |  saturate(0.5)  }}")
        (color11 . "{{ color11 |  saturate(0.5)  }}")
        (color12 . "{{ color12 |  saturate(0.5) }}")
        (color13 . "{{ color13 |  saturate(0.5) }}")
        (color14 . "{{ color14 |  saturate(0.5) }}")
        (color15 . "{{ color15 |  saturate(0.5) }}")
        (bg-alt . "{{ background | darken(0.3) }}")
        (fg-alt . "{{ foreground | darken(0.1) }}")
        (base0 . "{{ background | darken(0.5) }}")
        (base1 . "{{ background | darken(0.4) }}")
        (base2 . "{{ background | darken(0.2) }}")
        (base3 . "{{ background | darken(0.1) }}")
        (base4 . "{{ background | blend(foreground) }}")
        (base5 . "{{ background | blend(foreground) | lighten(0.1)  }}")
        (base6 . "{{ background | blend(foreground) | lighten(0.2) }}")
        (base7 . "{{ foreground | lighten(0.15) }}")
        (base8 . "{{ foreground | lighten(0.35) }}")
        (selection . "{{ background | blend(color4) }}")
        (line . "{{ background | darken(0.2) }}")
        (comment . "{{ color4 | blend(foreground) }}")
        (doc . "{{ (color4 | blend(foreground)) | lighten(0.15) }}")))
