;;; doom-wallust-colors.el --- Generated by Wallust -*- lexical-binding: t; -*-
;;
;; This file is auto-generated by Wallust's template engine.  Do not edit by hand.
;;

{% set bg = background %}
{% set fg = foreground %}
{% set cursor_color = cursor %}

(setq doom-wallust-generated-palette
      '((background . "{{ bg }}")
        (foreground . "{{ fg }}")
        (cursor . "{{ cursor_color }}")
        (color0 . "{{ color0 }}")
        (color1 . "{{ color1 | darken(0.12) }}")
        (color2 . "{{ color2 | darken(0.12) }}")
        (color3 . "{{ color3 | darken(0.12) }}")
        (color4 . "{{ color4 }}")
        (color5 . "{{ color5 }}")
        (color6 . "{{ color6 }}")
        (color7 . "{{ color7 }}")
        (color8 . "{{ color8 }}")
        (color9 . "{{ color9 | darken(0.08) }}")
        (color10 . "{{ color10 | darken(0.08) }}")
        (color11 . "{{ color11 | darken(0.08) }}")
        (color12 . "{{ color12 }}")
        (color13 . "{{ color13 }}")
        (color14 . "{{ color14 }}")
        (color15 . "{{ color15 }}")
        (bg-alt . "{{ background | darken(0.15) }}")
        (fg-alt . "{{ foreground | darken(0.1) }}")
        (base0 . "{{ background | darken(0.35) }}")
        (base1 . "{{ background | darken(0.25) }}")
        (base2 . "{{ background | darken(0.18) }}")
        (base3 . "{{ background | darken(0.12) }}")
        (base4 . "{{ background | lighten(0.12) }}")
        (base5 . "{{ color8 | blend(foreground) }}")
        (base6 . "{{ background | lighten(0.25) }}")
        (base7 . "{{ background | lighten(0.35) }}")
        (base8 . "{{ foreground | lighten(0.15) }}")
        (selection . "{{ background | blend(color4) }}")
        (line . "{{ background | darken(0.2) }}")
        (comment . "{{ color8 | blend(foreground) }}")
        (doc . "{{ (color8 | blend(foreground)) | lighten(0.15) }}")))
